services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: question_db
       MYSQL_USER: user
       MYSQL_PASSWORD: pass
    ports:
        - '3333:3306'
    volumes:
        - ./mysql_data:/var/lib/mysql
    networks:
        - spring-mysql

  springboot:
    build: .
    container_name: QuestionServiceApp
    environment:
      SERVER_PORT: 8080
      MYSQL_HOST: mysql 
      MYSQL_PORT: 3306 
      MYSQL_DB: question_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
        - "8081:8080"
    networks:
        - spring-mysql

volumes:
    mysql_data:

networks:
    spring-mysql:
        driver : bridge